name: ticker_free_circular_progress_indicator
description: A hot-restart safe circular progress indicator that doesn't use TickerProviderStateMixin, using manual frame callbacks for animations.
version: 3.0.0
homepage: https://github.com/SoundSliced/ticker_free_circular_progress_indicator
repository: https://github.com/SoundSliced/ticker_free_circular_progress_indicator
issue_tracker: https://github.com/SoundSliced/ticker_free_circular_progress_indicator/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
